"""Repeatable live demo; saves actual output, never substitutes mock replies."""

import argparse
import contextlib
import io
import json
import sys
import tempfile
from pathlib import Path
from unittest.mock import patch

import multi_agent as app


PROMPTS = [
    "What is 250 * 3?",
    "Thanks!",
    "Add 50 to that result.",
    "Save a note: Practice Python daily.",
    "List my saved notes.",
    "What is the current date and time in India?",
    "What is 10 divided by zero?",
]


class Tee(io.TextIOBase):
    """Show output in the terminal and save the same text to a file."""

    def __init__(self, terminal, file):
        self.terminal, self.file = terminal, file

    def write(self, text):
        self.terminal.write(text)
        self.file.write(text)
        self.flush()
        return len(text)

    def flush(self):
        self.terminal.flush()
        self.file.flush()


def error_examples():
    print("\nDELIBERATELY INJECTED invalid calls (not generated by the model)")
    for name, arguments in [("missing_tool", {}), ("calculate", {"expression": 8}),
                            ("notes", {"action": "delete"}), ("notes", "not JSON")]:
        call = {"function": {"name": name, "arguments": arguments}}
        print("[tool call] " + json.dumps(call))
        print("[tool result] " + json.dumps(app.dispatch(call)[1]))
    print("Program is still running after all four invalid calls.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default="llama3.2")
    parser.add_argument("--errors-only", action="store_true")
    args = parser.parse_args()
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    folder = Path(__file__).resolve().parent / "recordings"
    folder.mkdir(exist_ok=True)
    filename = "error-demo.txt" if args.errors_only else "live-demo.txt"
    with (folder / filename).open("w", encoding="utf-8") as output:
        with contextlib.redirect_stdout(Tee(sys.stdout, output)):
            error_examples()
            if args.errors_only:
                return 0
            print("\nLIVE OLLAMA DEMO | model: " + args.model)
            print("No mocked model responses. Temporary demo notebook only.")
            messages = [{"role": "system", "content": app.SYSTEM}]
            with tempfile.TemporaryDirectory() as temporary:
                with patch.object(app, "NOTES_FILE", Path(temporary) / "notes.json"):
                    for question in PROMPTS:
                        print("\nYou: " + question, flush=True)
                        messages.append({"role": "user", "content": question})
                        try:
                            print("Agent: " + app.run_turn(messages, args.model), flush=True)
                        except RuntimeError as exc:
                            print("DEMO STOPPED: " + str(exc))
                            return 1
            print("\nDemo finished. Inspect replies and tool logs before submitting.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
